apps/ppp/urls.py
from django.urls import path
from django.views.generic import RedirectView

from ppp.views import AddPPPRegistrationProtocolView, SavedPPPRegistrationProtocolListView, \
    EditPPPRegistrationProtocolView, PendingPPPRegistrationProtocolListView, PPPRegistrationProtocolListView, \
    PdfVersionView, DownloadListInExcelView

urlpatterns = [
    path('registration-protocol/add/', AddPPPRegistrationProtocolView.as_view(), name='add_ppp_registration_protocol'),
    path('registration-protocol/<int:pk>/edit/', EditPPPRegistrationProtocolView.as_view(), name='edit_ppp_registration_protocol'),
    path('registration-protocols/saved-list/', SavedPPPRegistrationProtocolListView.as_view(), name='saved_ppp_registration_protocols_list'),
    path('registration-protocols/pending-list/', PendingPPPRegistrationProtocolListView.as_view(), name='pending_ppp_registration_protocols_list'),
    path('registration-protocols/list/', PPPRegistrationProtocolListView.as_view(), name='ppp_registration_protocols_list'),
    path('registration-protocols/<slug:number>/pdf/', PdfVersionView.as_view(), name='pdf_of_ppp_registration_protocol'),
    path('registration-protocols/download-in-excel/', DownloadListInExcelView.as_view(), name='ppp_registration_protocol_download_in_excel'),
]

core/urls.py
from django.conf.global_settings import STATIC_ROOT
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.settings import STATIC_URL, MEDIA_URL, MEDIA_ROOT, DEBUG
from django.conf import urls
import debug_toolbar
from invoice.api.didox.views import DidoxLoginView, DidoxProfileView

urls.handler404 = 'administration.views.error_404_handler'
admin.site.site_header = "eFito Administration"
admin.site.site_title = "eFito Administration Portal"
admin.site.index_title = "Database management"
API_TITLE = 'API title'
API_DESCRIPTION = '...'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('ppp/', include(('ppp.urls', 'ppp'), namespace='ppp')),
    path('didox/login/', DidoxLoginView.as_view(), name='didox_login'),
    path('didox/<slug:tin>/profile/', DidoxProfileView.as_view(), name='didox_profile'),
]

if DEBUG:
    urlpatterns += path('stats/', include(debug_toolbar.urls)),
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

apps/ppp/views.py
import datetime
import io
import locale
import os

import qrcode
import xlwt
from PyPDF2 import PdfFileReader, PdfFileWriter
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

from administration.models import Country, SMSNotification
from administration.statuses import SMSNotificationStatuses, SMSNotificationPurposes
from ppp.models import Biocide, UNIT_CHOICES, PPPRegistrationProtocol, PPPRegistrationProtocolScope
from ppp.statuses import PPPProtocolStatuses


class AddPPPRegistrationProtocolView(TemplateView):
    template_name = 'ppp/protocol/add.html'

    def get(self, request):
        form = None
        return render(request, self.template_name, {
            'form': form,
            'countries': Country.objects.all().order_by('name_ru'),
            'biocides': Biocide.objects.all(),
            'units': UNIT_CHOICES
        })

    def post(self, request, *args, **kwargs):
        post = request.POST
        user = request.user
        if user.has_perm('ppp.add_ppp_registration_protocols'):
            with transaction.atomic():
                plant_type_uz = post.getlist('plant_type_uz[]')
                plant_type_ru = post.getlist('plant_type_ru[]')
                harmful_organisms_uz = post.getlist('harmful_organisms_uz[]')
                harmful_organisms_ru = post.getlist('harmful_organisms_ru[]')
                amount = post.getlist('amount[]')
                unit = post.getlist('unit[]')
                scope_uz = post.getlist('scope_uz[]')
                scope_ru = post.getlist('scope_ru[]')
                day = post.getlist('day[]')
                time = post.getlist('time[]')
                if len(plant_type_uz) > 0 and len(plant_type_uz) == len(plant_type_ru) == len(harmful_organisms_uz) == \
                        len(harmful_organisms_ru) == len(amount) == len(unit) == len(scope_uz) == len(scope_ru):
                    try:
                        ppp_registration_protocol = PPPRegistrationProtocol.objects.create(
                            serial_number=post.get('serial_number'),
                            expire_date=post.get('expire_date'),
                            protocol_number=post.get('protocol_number'),
                            protocol_given_date=post.get('protocol_given_date'),
                            country_id=post.get('country_id'),
                            applicant_tin=post.get('applicant_tin'),
                            applicant_name=post.get('applicant_name'),
                            applicant_phone=post.get('applicant_phone'),
                            biocide_id=post.get('biocide_id'),
                            biocide_trade_name=post.get('biocide_trade_name'),
                            concentration=post.get('concentration'),
                            irritant_substance=post.get('irritant_substance'),
                            registerer=user
                        )

                        if ppp_registration_protocol:
                            for index in range(0, len(plant_type_uz)):
                                PPPRegistrationProtocolScope.objects.create(
                                    ppp_registration_protocol=ppp_registration_protocol,
                                    plant_type_uz=plant_type_uz[index],
                                    plant_type_ru=plant_type_ru[index],
                                    harmful_organisms_uz=harmful_organisms_uz[index],
                                    harmful_organisms_ru=harmful_organisms_ru[index],
                                    amount=amount[index],
                                    unit=unit[index],
                                    scope_uz=scope_uz[index],
                                    scope_ru=scope_ru[index],
                                    day=day[index] if day[index] else None,
                                    time=time[index] if time[index] else None,
                                )
                        messages.success(request, 'Муваффақиятли сақланди.')
                        return HttpResponseRedirect(reverse('ppp:saved_ppp_registration_protocols_list'))
                    except Exception as e:
                        messages.error(request, e)
                        return HttpResponseRedirect(reverse('ppp:saved_ppp_registration_protocols_list'))
                else:
                    messages.error(request, 'Қўллаш доираси формасини тўлдиришда хатолик бор.')
                    return HttpResponseRedirect(reverse('ppp:saved_ppp_registration_protocols_list'))
        else:
            messages.error(request, 'Доступ закрыт!')
            return HttpResponseRedirect(reverse('administration:logout'))


class SavedPPPRegistrationProtocolListView(TemplateView):
    template_name = 'ppp/protocol/saved_list.html'

    def get(self, request):
        user = request.user

        if user.has_perm('ppp.send_to_approve_ppp_registration_protocols') or user.has_perm('ppp.approve_ppp_registration_protocols'):
            protocols = PPPRegistrationProtocol.all_objects.filter(status=PPPProtocolStatuses.SAVED)
        elif user.has_perm('ppp.add_ppp_registration_protocols'):
            protocols = PPPRegistrationProtocol.all_objects.filter(status=PPPProtocolStatuses.SAVED, registerer=user)

        if request.GET.get('applicant_name'):
            protocols = protocols.filter(applicant_name__contains=request.GET.get('applicant_name'))

        paginator = Paginator(protocols, 10)
        page = request.GET.get('page') if request.GET.get('page') else 1
        try:
            protocols = paginator.page(page)
        except PageNotAnInteger:
            protocols = paginator.page(1)
        except EmptyPage:
            protocols = paginator.page(paginator.num_pages)
        if not protocols:
            messages.warning(request, '<i class="fas fa-ban"> Сақланган гувоҳномалар топилмади</i>')
        return render(request, self.template_name, {
            'page': int(page),
            'protocols': protocols,
            'total_num_of_protocols': paginator.count,
            'num_pages': range(1, paginator.num_pages + 1)
        })


class EditPPPRegistrationProtocolView(TemplateView):
    template_name = 'ppp/protocol/edit.html'

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        redirect_url = reverse('ppp:edit_ppp_registration_protocol', kwargs={'pk': kwargs.get('pk')})
        try:
            if user.has_perm('ppp.approve_ppp_registration_protocols'):
                protocol = PPPRegistrationProtocol.all_objects.get(status=PPPProtocolStatuses.PENDING, pk=kwargs.get('pk'))
            elif user.has_perm('ppp.send_to_approve_ppp_registration_protocols'):
                protocol = PPPRegistrationProtocol.all_objects.get(status=PPPProtocolStatuses.SAVED,
                                                                   pk=kwargs.get('pk'))
            elif user.has_perm('ppp.add_ppp_registration_protocols'):
                protocol = PPPRegistrationProtocol.all_objects.get(status=PPPProtocolStatuses.SAVED, registerer=request.user, pk=kwargs.get('pk'))
            else:
                messages.error(request, 'Рухсат йўқ.')
                return HttpResponseRedirect(reverse('administration:logout'))

            kwargs.update({'protocol': protocol, 'redirect_url': redirect_url})
            return super(EditPPPRegistrationProtocolView, self).dispatch(request, *args, **kwargs)
        except Exception as e:
            messages.error(request, e)
            return HttpResponseRedirect(reverse('ppp:saved_ppp_registration_protocols_list'))

    def get(self, request, **kwargs):
        return render(request, self.template_name, {
            'protocol': kwargs.get('protocol'),
            'scopes': kwargs.get('protocol').scopes.all(),
            'countries': Country.objects.all().order_by('name_ru'),
            'biocides': Biocide.objects.all(),
            'units': UNIT_CHOICES,
            'protocol_statuses': PPPProtocolStatuses
        })

    def post(self, request, *args, **kwargs):

        protocol = kwargs.get('protocol')
        redirect_url = kwargs.get('redirect_url')
        post = request.POST

        if post.get('submission_purpose') == 'delete' and protocol.status == PPPProtocolStatuses.SAVED:
            protocol.delete()
            messages.success(request, 'Муваффақиятли ўчирилди.')
            return HttpResponseRedirect(redirect_url)

        if post.get('submission_purpose') == 'sent_to_back' and protocol.status == PPPProtocolStatuses.PENDING:
            protocol.status = PPPProtocolStatuses.SAVED
            protocol.save()
            messages.success(request, 'Муваффақиятли ортга қайтарилди.')
            return HttpResponseRedirect(redirect_url)

        with transaction.atomic():
            protocol.scopes.all().delete()
            try:
                protocol.serial_number = post.get('serial_number')
                protocol.expire_date = post.get('expire_date')
                protocol.protocol_number = post.get('protocol_number')
                protocol.protocol_given_date = post.get('protocol_given_date')
                protocol.country_id = post.get('country_id')
                protocol.applicant_tin = post.get('applicant_tin')
                protocol.applicant_name = post.get('applicant_name')

templates/ppp/protocol/list.html
{% extends 'general/base.html' %}
{% load staticfiles %}
{% load base %}
{% load general %}
{% block body %}
{% user_groups request.user as user_groups %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <form class="form-horizontal" action="{% url 'ppp:ppp_registration_protocol_download_in_excel' %}" method="get">
                {% csrf_token %}
              <div class="row">
                <div class="col-lg-3 col-md-12 col-sm-12">
                    <div class="form-group">
                        <input type="date" name="beginning_of_interval" id="beginning_of_interval" onfocusout="myFunction()" class="form-control">
                    </div>
                </div>
                <div class="col-lg-3 col-md-12 col-sm-12">
                    <div class="form-group">
                        <input type="date" name="end_of_interval" id="end_of_interval" class="form-control" max="NaN-NaN-NaN">
                    </div>
                </div>
                <div class="form-group col-lg-4 col-md-3 col-sm-12">
                    <select class="form-control" id="sel1" name="biocide_id" required="">
                        <option value="" disabled="" selected="">Препарат шаклини танлаш</option>
                        <option value="all">Барчаси</option>
                        {% for biocide in biocides%}
                        <option value="{{biocide.id}}">{{biocide.code}} - {{biocide.name_uz}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col-lg-2 col-md-2 col-sm-12">
                    <button type="submit" class="btn btn-info form-control"><i class="fas fa-download"></i></button>
                </div>
              </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    {% if protocols %}
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" ><strong>ГУВОҲНОМАЛАР</strong></h3>
                    <style>
                    .filter form {
                        display: inline-block;
                    }
                    </style>
                <div class="filter float-right">
                    <form>
                        <div class="input-group input-group-sm" style="width: 250px;">
                            <input required name="number" class="form-control float-right"
                                   placeholder="Рақами">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr role="row">
                            <th>№</th>
                            <th>Рақами</th>
                            <th>Берилган санаси</th>
                            <th>Амал қилиш муддати</th>
                            <th>Пртокол рақами</th>
                            <th>Пртокол санаси</th>
                            <th>Давлат</th>
                            <th>Ташкилот номи</th>
                            <th>Савдо номи</th>
                            <th>Препарат шакли</th>
                            <th>Рўйхатдан ўтқазилган вақти</th>
                            <th><i class="fas fa-eye fa-lg"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for protocol in protocols %}
                        <tr style="{% if tbotd.ikr_shipment.status == 4 %}background-color:#f39c12;{% elif tbotd.ikr_shipment.status == 9 %}background-color:#00a65a;{% elif tbotd.ikr_shipment.status == 7 or tbotd.ikr_shipment.status == 8 %}background-color:#dd4b39;{% endif %}">
                            <td>{{ forloop.counter|add:protocols.start_index|add:"-1" }}</td>
                            <td>{{protocol.number}}</td>
                            <td>{{protocol.given_date}}</td>
                            <td>{{protocol.expire_date}}</td>
                            <td>{{protocol.protocol_number}}</td>
                            <td>{{protocol.protocol_given_date}}</td>
                            <td>{{protocol.country.name_local}}</td>
                            <td>
                                {{protocol.applicant_name}}
                                <br>
                                {{protocol.applicant_tin}}
                            </td>
                            <td>{{protocol.biocide_trade_name}}</td>
                            <td>{{protocol.biocide.code}} - {{protocol.biocide.name_uz}} <br> ({{protocol.biocide_registered_number}})</td>
                            <td>{{protocol.added_at|date:"d-m-Y h:m"}}</td>
                            <td>
                                <a href="{% url 'ppp:pdf_of_ppp_registration_protocol' protocol.number %}" target="_blank"><i class="fas fa-eye fa-lg"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
                <span class="font-italic">Найдено {{total_num_of_protocols}} записей</span>
                <ul class="pull-right float-right">
                <div class="input-group pull-right float-right">
                    <div class="input-group-append">
                        <a href="{% url_args 1 'page' request.GET.urlencode %}" class="btn btn-default text-blue">в начало </a>
                        <a {% if protocols.has_previous %} href="{% url_args protocols.previous_page_number 'page' request.GET.urlencode %}" class="btn btn-default text-blue"{% else %} class="btn btn-default" {% endif %}>Предыдущий </a>
                    </div>
                    <select class="form-control" style="max-width:70px;" onchange="location = this.value;">
                        {% for num_page in num_pages %}
                            <option value="{% url_args num_page 'page' request.GET.urlencode %}" {% if num_page == page %} selected {% endif %}>{{ num_page }}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-append">
                        <a {% if protocols.has_next %} href="{% url_args protocols.next_page_number 'page' request.GET.urlencode %}" class="btn btn-default text-blue"{% else %} class="btn btn-default" {% endif %}> Следующий</a>
                        <a href="{% url_args protocols.paginator.num_pages 'page' request.GET.urlencode %}" class="btn btn-default text-blue"> Конец</a>
                    </div>
                </div>
                </ul>
            </div>
        </div>
        <!-- /.card -->
    </div>
    {% endif %}
</div><!-- /.row -->
<script>
function myFunction() {
    var x = document.getElementById("beginning_of_interval").value;
    var needed=x.split("-")
    console.log(needed[0])
    var maxified = new Date(needed[0], needed[1], needed[2]);
    var dd = maxified.getDate();
    var mm = maxified.getMonth()+2; //January is 0!
    var yyyy = maxified.getFullYear();
    if(dd<10){
        dd='0'+dd
    }
    if(mm<10){
        mm='0'+mm
    }
    maxified= yyyy+'-'+mm+'-'+dd;
    console.log(maxified)
    document.getElementById("end_of_interval").setAttribute("max", maxified);
}
</script>
{% endblock %}

templates/ppp/protocol/pending_list.html
{% extends 'general/base.html' %}
{% load staticfiles %}
{% load base %}
{% load general %}
{% block body %}
{% user_groups request.user as user_groups %}
<div class="row">
    {% if protocols %}
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" ><strong>ГУВОҲНОМАЛАР</strong></h3>
                    <style>
                    .filter form {
                        display: inline-block;
                    }
                    </style>
                <div class="filter float-right">
                    <form>
                        <div class="input-group input-group-sm" style="width: 250px;">
                            <input required name="applicant_name" class="form-control float-right"
                                   placeholder="Субъекти номи">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr role="row">
                            <th>№</th>
                            <th>Сериа рақами</th>
                            <th>Пртокол рақами</th>
                            <th>Пртокол санаси</th>
                            <th>Давлат</th>
                            <th>Ташкилот номи</th>
                            <th>Савдо номи</th>
                            <th>Препарат шакли</th>
                            <th>Рўйхатга олувчи</th>
                            <th>Рўйхатдан ўтқазилган вақти</th>
                            <th><i class="fas fa-eye fa-lg"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for protocol in protocols %}
                        <tr style="{% if tbotd.ikr_shipment.status == 4 %}background-color:#f39c12;{% elif tbotd.ikr_shipment.status == 9 %}background-color:#00a65a;{% elif tbotd.ikr_shipment.status == 7 or tbotd.ikr_shipment.status == 8 %}background-color:#dd4b39;{% endif %}">
                            <td>{{ forloop.counter|add:protocols.start_index|add:"-1" }}</td>
                            <td>{{protocol.serial_number}}</td>
                            <td>{{protocol.protocol_number}}</td>
                            <td>{{protocol.protocol_given_date}}</td>
                            <td>{{protocol.country.name_local}}</td>
                            <td>
                                {{protocol.applicant_name}}
                                <br>
                                {{protocol.applicant_tin}}
                            </td>
                            <td>{{protocol.biocide_trade_name}}</td>
                            <td>{{protocol.biocide.code}} - {{protocol.biocide.name_uz}}</td>
                            <td>{{protocol.registerer.name_ru}} <br> {{protocol.registerer.phone}}</td>
                            <td>{{protocol.added_at|date:"d-m-Y h:m"}}</td>
                            <td>
                                <a href="{% url 'ppp:edit_ppp_registration_protocol' protocol.pk %}"><i class="fas fa-eye fa-lg"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
                <span class="font-italic">Найдено {{total_num_of_protocols}} записей</span>
                <ul class="pull-right float-right">
                <div class="input-group pull-right float-right">
                    <div class="input-group-append">
                        <a href="{% url_args 1 'page' request.GET.urlencode %}" class="btn btn-default text-blue">в начало </a>
                        <a {% if protocols.has_previous %} href="{% url_args protocols.previous_page_number 'page' request.GET.urlencode %}" class="btn btn-default text-blue"{% else %} class="btn btn-default" {% endif %}>Предыдущий </a>
                    </div>
                    <select class="form-control" style="max-width:70px;" onchange="location = this.value;">
                        {% for num_page in num_pages %}
                            <option value="{% url_args num_page 'page' request.GET.urlencode %}" {% if num_page == page %} selected {% endif %}>{{ num_page }}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-append">
                        <a {% if protocols.has_next %} href="{% url_args protocols.next_page_number 'page' request.GET.urlencode %}" class="btn btn-default text-blue"{% else %} class="btn btn-default" {% endif %}> Следующий</a>
                        <a href="{% url_args protocols.paginator.num_pages 'page' request.GET.urlencode %}" class="btn btn-default text-blue"> Конец</a>
                    </div>
                </div>
                </ul>
            </div>
        </div>
        <!-- /.card -->
    </div>
    {% endif %}
</div>
<!-- /.row -->
{% endblock %}

templates/ppp/protocol/saved_list.html
{% extends 'general/base.html' %}
{% load staticfiles %}
{% load base %}
{% load general %}
{% block body %}
{% user_groups request.user as user_groups %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <a href="{% url 'ppp:add_ppp_registration_protocol' %}" class="btn btn-info form-control">Янги гувоҳномани рўйхатдан ўтқазиш</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    {% if protocols %}
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" ><strong>ГУВОҲНОМАЛАР</strong></h3>
                    <style>
                    .filter form {
                        display: inline-block;
                    }
                    </style>
                <div class="filter float-right">
                    <form>
                        <div class="input-group input-group-sm" style="width: 250px;">
                            <input required name="applicant_name" class="form-control float-right"
                                   placeholder="Субъекти номи">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr role="row">
                            <th>№</th>
                            <th>Сериа рақами</th>
                            <th>Пртокол рақами</th>
                            <th>Пртокол санаси</th>
                            <th>Давлат</th>
                            <th>Ташкилот номи</th>
                            <th>Савдо номи</th>
                            <th>Препарат шакли</th>
                            <th>Рўйхатдан ўтқазилган вақти</th>
                            <th><i class="fas fa-eye fa-lg"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for protocol in protocols %}
                        <tr style="{% if tbotd.ikr_shipment.status == 4 %}background-color:#f39c12;{% elif tbotd.ikr_shipment.status == 9 %}background-color:#00a65a;{% elif tbotd.ikr_shipment.status == 7 or tbotd.ikr_shipment.status == 8 %}background-color:#dd4b39;{% endif %}">
                            <td>{{ forloop.counter|add:protocols.start_index|add:"-1" }}</td>
                            <td>{{protocol.serial_number}}</td>
                            <td>{{protocol.protocol_number}}</td>
                            <td>{{protocol.protocol_given_date}}</td>
                            <td>{{protocol.country.name_local}}</td>
                            <td>
                                {{protocol.applicant_name}}
                                <br>
                                {{protocol.applicant_tin}}
                            </td>
                            <td>{{protocol.biocide_trade_name}}</td>
                            <td>{{protocol.biocide.code}} - {{protocol.biocide.name_uz}}</td>
                            <td>{{protocol.added_at|date:"d-m-Y h:m"}}</td>
                            <td>
                                <a href="{% url 'ppp:edit_ppp_registration_protocol' protocol.pk %}"><i class="fas fa-eye fa-lg"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
                <span class="font-italic">Найдено {{total_num_of_protocols}} записей</span>
                <ul class="pull-right float-right">
                <div class="input-group pull-right float-right">
                    <div class="input-group-append">
                        <a href="{% url_args 1 'page' request.GET.urlencode %}" class="btn btn-default text-blue">в начало </a>
                        <a {% if protocols.has_previous %} href="{% url_args protocols.previous_page_number 'page' request.GET.urlencode %}" class="btn btn-default text-blue"{% else %} class="btn btn-default" {% endif %}>Предыдущий </a>
                    </div>
                    <select class="form-control" style="max-width:70px;" onchange="location = this.value;">
                        {% for num_page in num_pages %}
                            <option value="{% url_args num_page 'page' request.GET.urlencode %}" {% if num_page == page %} selected {% endif %}>{{ num_page }}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-append">
                        <a {% if protocols.has_next %} href="{% url_args protocols.next_page_number 'page' request.GET.urlencode %}" class="btn btn-default text-blue"{% else %} class="btn btn-default" {% endif %}> Следующий</a>
                        <a href="{% url_args protocols.paginator.num_pages 'page' request.GET.urlencode %}" class="btn btn-default text-blue"> Конец</a>
                    </div>
                </div>
                </ul>
            </div>
        </div>
        <!-- /.card -->
    </div>
    {% endif %}
</div>
<!-- /.row -->
{% endblock %}